services:
  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data